### ISSUE TITLE
Drop-down menus don't drop down

### ISSUE THREAD

**Issue by DonFlymoor** [GabrieleGiuseppini/Floating-Sandbox#41]
> This is great news!!!! Thank you so much for your dedication to make this work!!!!!!
> 
> Let's now go through the other issues. 
> 1) Can you describe again the canvas issue? Any chance you may take screenshots?
> 2) FPS: can you enable "extended status text" (CTRL^X) and take a screenshot of the various writings?
> 3) Crash: that is understandable, it's crashing in a new feature altogether :-) Can you reproduce it and provide me with the following?
> a) Output of `print *indexEntry`at that moment
> b) At the very moment it crashes, there should be a ".shipdatabase" file in the folder that the ship explorer is trying to open. Can you send that to me?
> 
> Also, I'd like to close this ticket ("build on ARM" now works!) and open individual tickets for the issues you're having. Would you be OK with that?
> 

_Originally posted by @GabrieleGiuseppini in https://github.com/GabrieleGiuseppini/Floating-Sandbox/issues/34#issuecomment-661938307_

**Comment by DonFlymoor** [comment]
Deleting the `.shipdatabase` file allows me to load more ships. When I have a tool and activate it, then the action is applied to *where I last clicked*. For instance, I use the hammer on the aft of the ship, and the hammer animation plays, but no holes appear. I then click on the foredeck with the hammer, and a hole appears *in the aft*, growing biger as I hold it down. Could this be related the GL canvas covering the dropdown menu?

Some more intresting behavior: when I open `Game Preferences` I can't see what's inside it - it looks like a screenshot of the place where it opened taken inside a wx popup. Strangely, when I press `ctrl + o` and the open menu opens, The `Game Preferences` shows what it should show.

I'm not sure what to make of this, the only differance I can see is that when the `Load Ship` menu is open, FS pauses.

**Comment by GabrieleGiuseppini** [comment]
Wait, before we move on to the next issue, you're saying that the issue with loading ships is resolved for good, now that you've deleted the .shipdatabase file?

**Comment by DonFlymoor** [comment]
I have to delete it every time I restart the game.

**Comment by GabrieleGiuseppini** [comment]
Well, the issue is that it doesn't take a second on every box - it takes 10-15 secs on mine, for example - you must have fast SSD's :-)

Can you send me a copy of that file - one on which the game crashes? I'd really appreciate it as it'll help me find issues with that code.

Also, I'm gonna try something for the canvas issue. I'm in the middle of a final work item, after which I'll push that test. Stay tuned.

**Comment by DonFlymoor** [comment]
Here is the file:
[file.zip](https://github.com/GabrieleGiuseppini/Floating-Sandbox/files/4956881/file.zip)
I had to zip it for github to accept it.

**Comment by GabrieleGiuseppini** [comment]
Thank you for the file. I'll get that fixed.

Regarding drop-down menus, I've temporarily disabled SwapBuffers as an experiment - can you try with my last commit and see if menus appear again? Note that nothing will be rendered, this is just a test to see if it's the canvas getting in the way or not.

**Comment by DonFlymoor** [comment]
The GLcanvas did not render, but the menu buttons did not show the dropdown menus. They worked as far as clicking on them, but they did not appear. Note: the load ship box is the only wxwidgets box which I can see. I can open it by clicking `file`, then clicking right below `file`, or with ctrl+o

**Comment by GabrieleGiuseppini** [comment]
Thanks for trying that. No, I'm not using any custom buttons. Are you saying that you also can't see any of the following?
* Preferences (CTRL^F)
* Settings (CTRL^S)
* About (F2)
* Help (F1)
* Log (CTRL^L)
?

Also,can you try to run under gdb at the moment a window should open but it doesn't, to see if there's any assert's being fired?

**Comment by DonFlymoor** [comment]
None of those work, at least nothing is rendered in them.
Here is the gdb log from opening Preferences:
```gdb
(FloatingSandbox:9386): Gtk-CRITICAL **: 10:14:58.672: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```

And all the othor gtk errors:
```gdb
(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:13:48.385: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:13:48.385: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:13:48.386: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:13:48.386: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

[snip]


(FloatingSandbox:9386): Gtk-CRITICAL **: 10:14:05.148: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FloatingSandbox:9386): Gtk-CRITICAL **: 10:14:05.148: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
[New Thread 0xc85c71f0 (LWP 9482)]
[Thread 0xece451f0 (LWP 9422) exited]
[Thread 0xc85c71f0 (LWP 9482) exited]

(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:14:23.798: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:14:23.798: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:14:23.798: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:14:23.798: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:14:23.800: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:14:23.800: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:9386): GLib-GObject-WARNING **: 10:14:23.800: invalid (NULL) pointer instance

(FloatingSandbox:9386): GLib-GObject-CRITICAL **: 10:14:23.800: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

```

And a screenshot of opening Preferences:
![2020-07-24-101417_1920x1080_scrot](https://user-images.githubusercontent.com/36929174/88401029-2f90dc80-cd97-11ea-86cb-ee25cb0ec307.png)

**Comment by DonFlymoor** [comment]
Also, FS does not start rendering until the popup tip is closed, and if the popup tip is disabled, FS crashes when it would normally open it.

**Comment by GabrieleGiuseppini** [comment]
Can you give me a stack of the last crash you describe?

Regarding the menu, I'm afraid we're gonna have to start from the basics, may be with a simple minimal source file that I provide and that you'll have to compile with wxWidgets to see if it's an issue with wxWidgets or with FS instead. Which version of wxWidgets are you using, and how did you get it - did you build it yourself?

**Comment by DonFlymoor** [comment]
- Since FS requires a newer version of wxWidgets then is provided by my OS, I built it myself, version `3.1.3.0`. with gtk v.3 and using clang as the compiler

- FS did not crash without the popup tip, but the menubar buttons didn't appear at all -  the `File Controls Tools Options Help` menu bar wasn't shown

**Comment by GabrieleGiuseppini** [comment]
Wait, you said that "... if the popup tip is disabled, FS crashes when it would normally open it" - did I misunderstand you?

I'm preparing a simple source file to reproduce the menu issues, stay tuned.

**Comment by GabrieleGiuseppini** [comment]
Ok, can you try to compile and link (with the wxWidgets library) this single source file? https://drive.google.com/file/d/1ojanLZWXH4ttkrWk7Iov564FmwxtVNN5/view?usp=sharing

The executable should open a frame with a menu bar, with two menu items. Let me know how this test goes, we'll take it from there.

**Comment by DonFlymoor** [comment]
> Wait, you said that "... if the popup tip is disabled, FS crashes when it would normally open it" - did I misunderstand you?
> 
> I'm preparing a simple source file to reproduce the menu issues, stay tuned.

Yes, I did say that. But with buffer swap disabled, the behavior is not repeated.

**Comment by DonFlymoor** [comment]
The file you sent is from 1998... I can't compile it, I think it's for an ancient version of wxWidgets.

**Comment by GabrieleGiuseppini** [comment]
That's the header from a sample of wxWidgets, I've just built that file with VS2019. What errors do you get? Would a CMakeLists file help?

**Comment by DonFlymoor** [comment]
I believe a CMakeLists file might help, and I am recompiling wxWidgets with gtk3. A few days ago I tried to compile wxWidgets with x11, with is three years old, so it failed and may have broken wxWidgets.

**Comment by GabrieleGiuseppini** [comment]
Ouch. Good idea. Two tips:
* Do not enable UNICODE (not ready yet, will be soon)
* Enable (at least the) PNG image handler (`--with-libpng=builtin`)

**Comment by GabrieleGiuseppini** [comment]
Two CMake files attached, put them in the same directory where the .cpp file is.
[CMakeLists.txt](https://github.com/GabrieleGiuseppini/Floating-Sandbox/files/4973575/CMakeLists.txt)

**Comment by DonFlymoor** [comment]
I'll do that when wxWidgets finishes compiling! I'm trying to build in RAM, as the "hard drive" on a pi is an SD card.

**Comment by DonFlymoor** [comment]
The menu for that program works.

**Comment by GabrieleGiuseppini** [comment]
Perfect, thanks. Tomorrow I'm gonna have another test. We're getting there.

**Comment by GabrieleGiuseppini** [comment]
Silly question - have you tried re-building FS now that you have new, shiny wxWidgets?

**Comment by DonFlymoor** [comment]
I rebuilt with the "old and revised" wxWidgets, and the dropdown menu still doesn't render. On a positive note, it's crashing when the popup tip is disabled, the tool shortcut keys aren't working, and the interactions are still "one click behind"

**Comment by GabrieleGiuseppini** [comment]
Darn. And I like the positive note :-)

I'll have another test soon, with multi-threading disabled, to see if that's responsible. Can you send me the stack of the crash happening when the popup is disabled?

**Comment by GabrieleGiuseppini** [comment]
I've just pushed an experimental change that disables multi-threaded rendering. Can you check if menu's are now shown?

Also, I'd really appreciate the stack of that crash happening when the startup tip popup is disabled :-) That should tell us a lot about what's going on.

**Comment by GabrieleGiuseppini** [comment]
Edit: I have *just now* merged into `master`, and I have re-applied the hack to disable multi-threaded rendering. Please checkout `master`, pull, and re-build from there. We'll be working out of `master` for the next few days.

**Comment by DonFlymoor** [comment]
Great! I'll do that.

**Comment by GabrieleGiuseppini** [comment]
Hi, any news on this?

**Comment by DonFlymoor** [comment]
Fs compiled with an error related to using `abs` instead of `std::abs`, but replacing that allowed it to complete. I noticed that the Titanic now has lights on the cabins, and an electrical panel, but everything seemed to work as well as it had before the merge.

**Comment by GabrieleGiuseppini** [comment]
Do you get the menus now?

**Comment by DonFlymoor** [comment]
No, unfortunately the menus are still unrendered, the keyboard shortcuts don't work except for the ctrl ones, the simulation is still "one click behind", and the electrical panel plays havoc with the GL canvas.

**Comment by GabrieleGiuseppini** [comment]
Well, on one side this is great news - it definitely means that multithreading has nothing to do with these issues.

Let's proceed by tentatives then. If you open FloatingSandbox/MainFrame.cpp, you should see a try-catch block starting at line 1082 - there's a comment preceding that saying "Run a game step". Can you comment out the whole try-catch block, build, and see if the UI starts working? 

Note that there won't be any "game" after this change - it'll be pure UI, we're trying to see if it's the simulation somehow that's at odds with the UI controls.

**Comment by DonFlymoor** [comment]
Commenting that out caused the splash screen to "hang", and the popup to popup. Other then that, nothing happened, no UI, no canvas... I got the same behavior by **just** commenting out the Render line in that try block.

**Comment by GabrieleGiuseppini** [comment]
With "popup" you mean the "startup tip" popup, right? And what happens when you dismiss the popup?

**Comment by DonFlymoor** [comment]
Yes, the startup tip. Nothing happens when I dismiss it, the splash screen just keeps hanging.

**Comment by GabrieleGiuseppini** [comment]
Got it, thank you, a last test: please revert to `MainFrame.cpp` from master, then comment out only line 1094. The UI should appear now, with menu's and all. Let me know how it goes!

**Comment by DonFlymoor** [comment]
It worked! All previous problems are fixed! The buttons work, the shortcuts... Except for the fact that there is no ship... or water...

**Comment by GabrieleGiuseppini** [comment]
Great, thanks for trying that out. We're getting somewhere, but we need to cast some finer nets in order to figure out exactly what's causing this issue.
To this end I've created a new branch, `issue_41`, with some changes that will help me figure this out. Could you get rid of all your local modifications, checkout this branch, rebuild, and run?
I'll need the following two things after your run:
1) Let me know whether the menu's and the other UI thinghies work or not (note that there won't be any ship nor world)
2) After closing the app, please send me the `last_run.log` log file - it should be somewhere below your `~` user directory, probably under a `Floating Sandbox\Diagnostics` directory

This will be the first of many similar steps. Let's get started!

**Comment by DonFlymoor** [comment]
Thanks for taking the time to try to solve this!
1. The menu, UI, and other wxWidgets based things aren't working correctly (exactly the same behavior of the `master` branch), So I don't think the problem is GL based. It looks to me like something is grabbing the user's input and output, but isn't handing them back correctly (Perhaps a Linux vs. Windows problem? Is the normal Linux version working correctly? If you have a Linux box, you could try an X11 version of Debian, which is what I am using. (The only difference is ARM vs. ADM) )

2. No `last_run.log` file has appeared, Just the normal user preference stuff, and the terminal output is the same as the `master` branch.

**Comment by GabrieleGiuseppini** [comment]
Thanks. 
1. I'll have to make a few more changes before you can retry. No, I don't have any Linux to try on, I have to wait for the new box to arrive before I can run a Linux VM, it'll take a few weeks.
2. We need to solve the log issue first, darn. Do you have a `Diagnostics` directory under `~\Floating Sandbox`? If so, what's in it? If not, can you create it manually (mind the capitalization) and re-try?

**Comment by DonFlymoor** [comment]
1. You could try [live booting Linux from a usb drive](https://www.linux.com/training-tutorials/live-booting-linux/#:~:text=One%20such%20tool%20is%20called,booting%20a%20live%20Linux%20distribution.), instead of a using a VM.
2. I can't find any `Diagnostics` directory under `~\Floating Sandbox`

**Comment by GabrieleGiuseppini** [comment]
1. My box is a 2009 one-core Dell laptop, it supports max USB 2.0 - I doubt I can run a VM on it without crawling to a halt :-)
2. I've pushed another change to understand what's going on with the log - I really need that working. Can you try with that? If it doesn't work, can you copy the terminal's stdout and send that to me?
3. Are you closing via the "Quit" menu entry? If not, can you close with it and see if the log is created?

**Comment by DonFlymoor** [comment]
1. Live booting is using a USB drive as a hard drive, so you can run Linux from a USB without affecting your hard drive. No emulation/VM required. USB 2.0 should work, it just may be slightly slower then 3.0 with disk speed. This article explains how to set up USB booting in detail: https://www.linux.com/training-tutorials/live-booting-linux/#:~:text=One%20such%20tool%20is%20called,booting%20a%20live%20Linux%20distribution.
2. I will try pulling and rebuilding, and I can defiantly send you the stdout if the log doesn't work.
3. I can't close via the `Quit` menu, as I can't see it - no dropdown menus work. I can try randomly clicking, and see if I can hit it...

**Comment by GabrieleGiuseppini** [comment]
I see, you're right - without menus you can't close cleanly, that's why there's no log. Have you tried ALT+F4? Or the close window button on the top-right (do you even get a close button?) If all else fails, a stdout dump will be fine.

**Comment by DonFlymoor** [comment]
Sorry it took so long! Here is the stdout from FS (Still no `Diagnostics` dir or log):
```bash
09:29:12.010181:OnMainGLCanvasResize: 20x20

09:29:12.045182:SplashScreenDialog::Show(): Completed

09:29:12.103365:SplashScreenDialog::OnPaint()

09:29:12.134556:TODOTEST: disabling multi-threaded rendering @ TaskThread

09:29:12.134758:TaskThread::TaskThread(): not starting thread - will be simulating multi-threading

09:29:12.139932:SplashScreenDialog::OnPaint()

09:29:12.146733:OpenGL version: 2.1

09:29:12.146936:GL_VENDOR=Broadcom

09:29:12.147035:GL_RENDERER=V3D 4.2

09:29:12.147214:Has GL_EXT_framebuffer_object: YES

09:29:12.147365:Has GL_ARB_draw_instanced: YES

09:29:12.147421:Has GL_ARB_vertex_array_object: YES

09:29:12.147497:Has GL_ARB_texture_float: YES

09:29:12.147596:GL_MAX_VERTEX_ATTRIBS=16

09:29:12.147669:GL_MAX_VIEWPORT_DIMS=4096x4096

09:29:12.147740:GL_MAX_TEXTURE_SIZE=4096

09:29:12.147816:GL_MAX_RENDERBUFFER_SIZE=4096

09:29:13.284351:SplashScreenDialog::OnPaint()

09:29:13.301996:SplashScreenDialog::OnPaint()

09:29:13.320952:Generic linear texture atlas size: 512x256

09:29:13.745713:Generic mipmapped texture atlas size: 4096x2048

09:29:14.047323:SplashScreenDialog::OnPaint()

09:29:15.069235:Explosion texture atlas size: 4096x4096

09:29:15.330390:SplashScreenDialog::OnPaint()

09:29:15.529444:Cloud texture atlas size: 2048x2048

09:29:15.600520:SplashScreenDialog::OnPaint()

<snip>

09:29:19.377259:SplashScreenDialog::OnPaint()


(FloatingSandbox:3183): GLib-GObject-WARNING **: 09:29:19.816: invalid (NULL) pointer instance

(FloatingSandbox:3183): GLib-GObject-CRITICAL **: 09:29:19.816: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:3183): GLib-GObject-WARNING **: 09:29:19.816: invalid (NULL) pointer instance

(FloatingSandbox:3183): GLib-GObject-CRITICAL **: 09:29:19.816: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
09:29:19.886737:SplashScreenDialog::OnPaint()

09:29:19.890979:SplashScreenDialog::OnPaint()

09:29:19.903938:SplashScreenDialog::OnPaint()

09:29:19.924560:SplashScreenDialog::OnPaint()

09:29:20.125162:Spring ACMR: original=0.52578, optimized=0.36242

09:29:20.181720:Created ship: W=234, H=67, 7654/11752buf points, 27424 springs, 13210 triangles, 1751 electrical elements.

09:29:20.242675:OnSwitchCreated(EEID=0:14 IID=10): State=0

09:29:20.255172:OnSwitchCreated(EEID=0:104 IID=9): State=0

09:29:20.260009:OnSwitchCreated(EEID=0:208 IID=4): State=1

09:29:20.263617:OnSwitchCreated(EEID=0:245 IID=3): State=1

09:29:20.266423:OnSwitchCreated(EEID=0:279 IID=2): State=1

09:29:20.269612:OnSwitchCreated(EEID=0:284 IID=1): State=1

09:29:20.272800:OnSwitchCreated(EEID=0:1055 IID=6): State=1

09:29:20.276077:OnSwitchCreated(EEID=0:1114 IID=5): State=1

09:29:20.279392:OnEngineMonitorCreated(EEID=0:1691 IID=7): Thrust=0 RPM=0

09:29:20.282056:OnEngineControllerCreated(EEID=0:1692 IID=0)

09:29:20.284856:OnPowerProbeCreated(EEID=0:1697 IID=8): State=1

09:29:20.288143:Layout: decoratedW=19, decoratedH=1, W=19, H=1

09:29:20.289314:OnMainGLCanvasResize: 20x0

09:29:20.290255:OnMainGLCanvasResize: 20x0

09:29:20.320320:SplashScreenDialog::OnPaint()

09:29:20.323852:Post-Initialize took 8.31103s

09:29:20.480896:TODOTEST: disabled rendering (upload+rendering) @ GameController

09:29:20.487464:MainFrame::AfterGameRender: showing frame

09:29:21.271939:OnMainGLCanvasResize: 398x22


(FloatingSandbox:3183): Gtk-CRITICAL **: 09:29:21.363: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
09:29:21.365242:OnMainGLCanvasResize: 2x0

09:29:21.374641:OnMainGLCanvasResize: 2x0

09:29:21.389600:OnMainGLCanvasResize: 2x0

09:29:21.634064:OnMainGLCanvasResize: 1920x883

09:29:21.634231:OnMainGLCanvasResize: 1920x883

09:29:21.636372:OnMainGLCanvasResize: 1920x882

09:29:21.636580:OnMainGLCanvasResize: 1920x882

09:29:21.738297:RenderContext::RebindContext: start

09:29:21.768732:RenderContext::RebindContext: end

09:29:21.768942:MainFrame::OnMainGLCanvasPaint(): Hiding SplashScreen

09:29:30.816184:UpdateChecker: StatusCode=403

An internal OpenAL call failed in SoundSource.cpp(75).
Expression:
   alSourcef(m_source, AL_GAIN, volume * 0.01f)
Error description:
   AL_INVALID_VALUE
   A numeric argument is out of range.

An internal OpenAL call failed in SoundSource.cpp(75).
Expression:
   alSourcef(m_source, AL_GAIN, volume * 0.01f)
Error description:
   AL_INVALID_VALUE
   A numeric argument is out of range.

09:30:49.826966:OnMainGLCanvasResize: 1920x852

09:30:49.827204:OnMainGLCanvasResize: 1920x852

09:30:49.827684:OnMainGLCanvasResize: 1920x852

09:30:49.929254:Thread exiting

09:30:49.929440:Thread exiting

09:30:49.929252:Thread exiting
```

**Comment by DonFlymoor** [comment]
> I see, you're right - without menus you can't close cleanly, that's why there's no log. Have you tried ALT+F4? Or the close window button on the top-right (do you even get a close button?) If all else fails, a stdout dump will be fine.

Pressing `esc` gives me a close button, and `Alt+F4` closes FS, but I can't seem to be able to hit the close button in the drop-down menu. Some behavior I observed which seems unusual, the user input is stored and each action seems to be executed every 1/2 second. If I click twenty times, then scroll down twice, the hammer "hits" twice a second for ten seconds, then the view zooms out once, waits half a second, then zooms out again. Could this behavior be related to the problem?

**Comment by GabrieleGiuseppini** [comment]
Thanks for the log! I'll soon push another change, and I'll ask you to run this again.

Regarding the behavior you observe, that is not on this "hacked" version, right? There's no rendering with this version, can you confirm? I can't think of anything at this moment that might cause that, other than a very slow message pump. How many FPS do you get?

**Comment by GabrieleGiuseppini** [comment]
Ok, I've pushed another change. Can you try now and let me know if the menus work? Also please let me have the log.

Be careful as the functionality is quite limited now, it may crash if you attempt to do things like using tools or change settings!

**Comment by DonFlymoor** [comment]
> Thanks for the log! I'll soon push another change, and I'll ask you to run this again.
> 
> Regarding the behavior you observe, that is not on this "hacked" version, right? There's no rendering with this version, can you confirm? I can't think of anything at this moment that might cause that, other than a very slow message pump. How many FPS do you get?

This is the original, non edited `issue_41` branch. Something in the function on line `1094` in `mainFrame.cpp` is breaking the menu. I can get 30 FPS, if I load one of the cars, but the menu problem still persists.

I will pull and build, then give you the results.

**Comment by DonFlymoor** [comment]
I'm afraid the modification was unsuccessful. The menu still does not work. Do you have any custom input handlers?

**Comment by GabrieleGiuseppini** [comment]
That is good news indeed. The goal of the modifications I'm making is to find what's breaking the UI. I'll soon have another modification - in the meantime, can you send me the log of this last run?

Let's worry about the input handling later - at this moment we can't even get wxWidgets to work properly, all bets are off with the rest of the code :-)

**Comment by GabrieleGiuseppini** [comment]
Hey, on a separate note - I'm reworking the in-game credits, and I'd like to credit you for your help with the Linux/X-Windows build. Which name would you rather use for the credits - "Don Flymoor"?

**Comment by DonFlymoor** [comment]
Don Flymoor is just a pseudonym, my real name is under my profile.

**Comment by GabrieleGiuseppini** [comment]
Great, do you prefer me to use your pseudonym or your real name?

**Comment by DonFlymoor** [comment]
You can use my real name for the credits.

**Comment by DonFlymoor** [comment]
Sorry it took so long for the log.

<details>
<summary>Here is the log:</summary>

```shell
11:04:54.359701:OnMainGLCanvasResize: 20x20

11:04:54.396881:SplashScreenDialog::Show(): Completed

11:04:54.428488:SplashScreenDialog::OnPaint()

11:04:54.524786:TODOTEST: disabling multi-threaded rendering @ TaskThread

11:04:54.524927:TaskThread::TaskThread(): not starting thread - will be simulating multi-threading

11:04:54.583920:SplashScreenDialog::OnPaint()

11:04:54.624308:OpenGL version: 2.1

11:04:54.624465:GL_VENDOR=Broadcom

11:04:54.624514:GL_RENDERER=V3D 4.2

11:04:54.624585:Has GL_EXT_framebuffer_object: YES

11:04:54.624677:Has GL_ARB_draw_instanced: YES

11:04:54.624724:Has GL_ARB_vertex_array_object: YES

11:04:54.624772:Has GL_ARB_texture_float: YES

11:04:54.624818:GL_MAX_VERTEX_ATTRIBS=16

11:04:54.624857:GL_MAX_VIEWPORT_DIMS=4096x4096

11:04:54.624896:GL_MAX_TEXTURE_SIZE=4096

11:04:54.624933:GL_MAX_RENDERBUFFER_SIZE=4096

11:04:54.626950:SplashScreenDialog::OnPaint()

11:04:55.789443:SplashScreenDialog::OnPaint()

11:04:55.818913:SplashScreenDialog::OnPaint()

11:04:55.849552:Generic linear texture atlas size: 512x256

11:04:56.311212:Generic mipmapped texture atlas size: 4096x2048

11:04:56.597017:SplashScreenDialog::OnPaint()

11:04:57.629370:Explosion texture atlas size: 4096x4096

11:04:57.889307:SplashScreenDialog::OnPaint()

11:04:58.099888:Cloud texture atlas size: 2048x2048

11:04:58.165323:SplashScreenDialog::OnPaint()

<snip>

11:05:03.062552:SplashScreenDialog::OnPaint()


(FloatingSandbox:3775): GLib-GObject-WARNING **: 11:05:03.534: invalid (NULL) pointer instance

(FloatingSandbox:3775): GLib-GObject-CRITICAL **: 11:05:03.534: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:3775): GLib-GObject-WARNING **: 11:05:03.534: invalid (NULL) pointer instance

(FloatingSandbox:3775): GLib-GObject-CRITICAL **: 11:05:03.534: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
11:05:03.588181:SplashScreenDialog::OnPaint()

11:05:03.606870:SplashScreenDialog::OnPaint()

11:05:03.623933:SplashScreenDialog::OnPaint()

11:05:03.651051:SplashScreenDialog::OnPaint()

11:05:03.871416:Spring ACMR: original=0.52578, optimized=0.36242

11:05:03.929201:Created ship: W=234, H=67, 7654/11752buf points, 27424 springs, 13210 triangles, 1751 electrical elements.

11:05:03.984662:OnSwitchCreated(EEID=0:14 IID=10): State=0

11:05:03.997732:OnSwitchCreated(EEID=0:104 IID=9): State=0

11:05:04.001046:OnSwitchCreated(EEID=0:208 IID=4): State=1

11:05:04.004027:OnSwitchCreated(EEID=0:245 IID=3): State=1

11:05:04.007034:OnSwitchCreated(EEID=0:279 IID=2): State=1

11:05:04.010015:OnSwitchCreated(EEID=0:284 IID=1): State=1

11:05:04.013019:OnSwitchCreated(EEID=0:1055 IID=6): State=1

11:05:04.016389:OnSwitchCreated(EEID=0:1114 IID=5): State=1

11:05:04.019551:OnEngineMonitorCreated(EEID=0:1691 IID=7): Thrust=0 RPM=0

11:05:04.022303:OnEngineControllerCreated(EEID=0:1692 IID=0)

11:05:04.025305:OnPowerProbeCreated(EEID=0:1697 IID=8): State=1

11:05:04.028125:Layout: decoratedW=19, decoratedH=1, W=19, H=1

11:05:04.029267:OnMainGLCanvasResize: 20x0

11:05:04.030118:OnMainGLCanvasResize: 20x0

11:05:04.033391:SplashScreenDialog::OnPaint()

11:05:04.043275:Post-Initialize took 9.68114s

11:05:04.197164:TODOTEST: disabled rendering (upload+rendering) @ GameController

11:05:04.208292:MainFrame::AfterGameRender: showing frame

11:05:04.980747:OnMainGLCanvasResize: 398x22


(FloatingSandbox:3775): Gtk-CRITICAL **: 11:05:05.014: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
11:05:05.015922:OnMainGLCanvasResize: 2x0

11:05:05.022985:OnMainGLCanvasResize: 2x0

11:05:05.026151:OnMainGLCanvasResize: 2x0

11:05:05.131268:OnMainGLCanvasResize: 1920x883

11:05:05.131479:OnMainGLCanvasResize: 1920x883

11:05:05.133167:OnMainGLCanvasResize: 1920x882

11:05:05.133342:OnMainGLCanvasResize: 1920x882

11:05:05.214813:RenderContext::RebindContext: start

11:05:05.245132:RenderContext::RebindContext: end

11:05:05.245377:MainFrame::OnMainGLCanvasPaint(): Hiding SplashScreen

11:05:14.798362:UpdateChecker: StatusCode=403
```
</details>

**Comment by GabrieleGiuseppini** [comment]
Great, thank you!

Another test now - can you pull from issue_41 again (`git pull --rebase`), rebuild, and run? Please don't forget the log/stdout dump!

**Comment by DonFlymoor** [comment]
I don't use `git` for large repos, as `svn` is more bandwidth-friendly (it has download resume support). I'll try `git svn pull --rebase`

**Comment by GabrieleGiuseppini** [comment]
Worst case you might nuke your clone completely and pull everything again from scratch.

P.S.: please don't forget the log/stdout dump!!!

**Comment by DonFlymoor** [comment]
## I successfully pulled, but unfortunately ran into a few errors while building:
<details>
<summery><strong>These are the errors</strong></summery>

```make
[  3%] Built target gtest
[ 10%] Built target GameCoreLib
[ 13%] Built target gmock
[ 13%] Built target GameOpenGLLib
[ 15%] Built target UIControlsLib
[ 19%] Built target GPUCalcLib
[ 22%] Built target GPUCalcTest
[ 23%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o
[ 23%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController.cpp.o
[ 24%] Building CXX object Game/CMakeFiles/GameLib.dir/NotificationLayer.cpp.o
[ 24%] Building CXX object Game/CMakeFiles/GameLib.dir/Bombs.cpp.o
[ 25%] Building CXX object Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o
[ 26%] Building CXX object Game/CMakeFiles/GameLib.dir/Clouds.cpp.o
[ 26%] Building CXX object Game/CMakeFiles/GameLib.dir/ElectricalElements.cpp.o
[ 27%] Building CXX object Game/CMakeFiles/GameLib.dir/AntiMatterBomb.cpp.o
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/AntiMatterBomb.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/AntiMatterBomb.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Clouds.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Clouds.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ElectricalElements.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ElectricalElements.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Bombs.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Bombs.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ShipBuilder.cpp:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ShipBuilder.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ShipBuilder.cpp:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/ShipBuilder.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Physics.h:30:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/Storm.h:10:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController_StateMachines.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.h:15:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController_StateMachines.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.h:15:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.h:15:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:81:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading texture group...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [25]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.cpp:6:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GameController.h:15:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/NotificationLayer.h:9:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/RenderContext.h:8:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/GlobalRenderContext.h:12:
In file included from /path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager.h:109:
/path/to/Floating-Sandbox//branches/issue_41/Game/UploadedTextureManager-inl.h:106:9: error: no matching function for call to object of type
      'const ProgressCallback' (aka 'const function<void (float, ProgressMessageType)>')
        progressCallback(currentFramesCount / totalFramesCount, "Loading textures...");
        ^~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/std_function.h:576:12: note: candidate function not viable: no known conversion from 'const char [20]' to 'ProgressMessageType' for 2nd argument
      _Res operator()(_ArgTypes... __args) const;
           ^
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:128: Game/CMakeFiles/GameLib.dir/NotificationLayer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:271: Game/CMakeFiles/GameLib.dir/Bombs.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:284: Game/CMakeFiles/GameLib.dir/Clouds.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:258: Game/CMakeFiles/GameLib.dir/AntiMatterBomb.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:297: Game/CMakeFiles/GameLib.dir/ElectricalElements.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:76: Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:63: Game/CMakeFiles/GameLib.dir/GameController.cpp.o] Error 1
2 errors generated.
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:167: Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:399: Game/CMakeFiles/GameLib.dir/all] Error 2
```
</details>

**Comment by GabrieleGiuseppini** [comment]
Sorry about that, it's two functions that are at the moment unused and VS doesn't even compile them, so I didn't catch the break. Pushed a fix.

**Comment by DonFlymoor** [comment]
One more error...

```make
In file included from /path/to/Floating-Sandbox//branches/issue_41/ShipTools/Main.cpp:7:
/path/to/Floating-Sandbox//branches/issue_41/ShipTools/Baker.h:44:29: error: no matching function for call to 'BuildRegularAtlas'
        auto textureAtlas = Render::TextureAtlasBuilder<typename TextureDatabaseTraits::TextureGroups>::BuildRegularAtlas(
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/Floating-Sandbox//branches/issue_41/ShipTools/Main.cpp:135:16: note: in instantiation of function template specialization
      'Baker::BakeRegularAtlas<Render::ExplosionTextureDatabaseTraits>' requested here
        Baker::BakeRegularAtlas<Render::ExplosionTextureDatabaseTraits>(
               ^
/path/to/Floating-Sandbox//branches/issue_41/GameCore/../Game/TextureAtlas.h:208:40: note: candidate function template not viable: no known conversion from
      '(lambda at /path/to/Floating-Sandbox//branches/issue_41/ShipTools/Baker.h:47:13)' to 'const ProgressCallback'
      (aka 'const function<void (float, ProgressMessageType)>') for 3rd argument
    static TextureAtlas<TextureGroups> BuildRegularAtlas(
                                       ^
1 error generated.
make[2]: *** [ShipTools/CMakeFiles/ShipTools.dir/build.make:76: ShipTools/CMakeFiles/ShipTools.dir/Main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by GabrieleGiuseppini** [comment]
Darn. Try again :-)

**Comment by DonFlymoor** [comment]
<details>
<summary>Same behavior as last time</summary>

```shell
18:13:25.664493:OnMainGLCanvasResize: 20x20

18:13:25.706160:SplashScreenDialog::Show(): Completed

18:13:25.752606:SplashScreenDialog::OnPaint()

18:13:25.801303:TODOTEST: disabling multi-threaded rendering @ TaskThread

18:13:25.801438:TaskThread::TaskThread(): not starting thread - will be simulating multi-threading

18:13:25.803823:SplashScreenDialog::OnPaint()

18:13:25.848917:OpenGL version: 2.1

18:13:25.849098:GL_VENDOR=Broadcom

18:13:25.849157:GL_RENDERER=V3D 4.2

18:13:25.849224:Has GL_EXT_framebuffer_object: YES

18:13:25.849319:Has GL_ARB_draw_instanced: YES

18:13:25.849382:Has GL_ARB_vertex_array_object: YES

18:13:25.849461:Has GL_ARB_texture_float: YES

18:13:25.849502:GL_MAX_VERTEX_ATTRIBS=16

18:13:25.849540:GL_MAX_VIEWPORT_DIMS=4096x4096

18:13:25.849592:GL_MAX_TEXTURE_SIZE=4096

18:13:25.849628:GL_MAX_RENDERBUFFER_SIZE=4096

18:13:25.851788:SplashScreenDialog::OnPaint()

18:13:26.979377:SplashScreenDialog::OnPaint()

18:13:27.009365:SplashScreenDialog::OnPaint()

18:13:27.036480:Generic linear texture atlas size: 512x256

18:13:27.455228:Generic mipmapped texture atlas size: 4096x2048

18:13:27.735707:SplashScreenDialog::OnPaint()

18:13:28.775247:Explosion texture atlas size: 4096x4096

18:13:29.027503:SplashScreenDialog::OnPaint()

18:13:29.236449:Cloud texture atlas size: 2048x2048

18:13:29.300588:SplashScreenDialog::OnPaint()

18:13:30.493974:SplashScreenDialog::OnPaint()

18:13:30.515885:SplashScreenDialog::OnPaint()

18:13:30.570274:SplashScreenDialog::OnPaint()

18:13:30.574402:Number of hardware threads: 4

18:13:30.589673:SplashScreenDialog::OnPaint()

18:13:30.663301:SplashScreenDialog::OnPaint()

18:13:30.684336:SplashScreenDialog::OnPaint()

18:13:30.714486:SplashScreenDialog::OnPaint()

18:13:30.735299:SplashScreenDialog::OnPaint()

18:13:30.749898:SplashScreenDialog::OnPaint()

18:13:30.767610:SplashScreenDialog::OnPaint()
```
\<snip\>

```shell
18:13:34.092880:SplashScreenDialog::OnPaint()

18:13:34.107954:SplashScreenDialog::OnPaint()

18:13:34.136584:SplashScreenDialog::OnPaint()

18:13:34.141961:SplashScreenDialog::OnPaint()

18:13:34.188785:SplashScreenDialog::OnPaint()

18:13:34.208897:SplashScreenDialog::OnPaint()

18:13:34.227363:SplashScreenDialog::OnPaint()


(FloatingSandbox:31193): GLib-GObject-WARNING **: 18:13:34.690: invalid (NULL) pointer instance

(FloatingSandbox:31193): GLib-GObject-CRITICAL **: 18:13:34.691: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(FloatingSandbox:31193): GLib-GObject-WARNING **: 18:13:34.691: invalid (NULL) pointer instance

(FloatingSandbox:31193): GLib-GObject-CRITICAL **: 18:13:34.691: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
18:13:34.744398:SplashScreenDialog::OnPaint()

18:13:34.763829:SplashScreenDialog::OnPaint()

18:13:34.780625:SplashScreenDialog::OnPaint()

18:13:34.807134:SplashScreenDialog::OnPaint()

18:13:35.034684:Spring ACMR: original=0.52578, optimized=0.36242

18:13:35.089996:Created ship: W=234, H=67, 7654/11752buf points, 27424 springs, 13210 triangles, 1751 electrical elements.

18:13:35.146298:OnSwitchCreated(EEID=0:14 IID=10): State=0

18:13:35.159956:OnSwitchCreated(EEID=0:104 IID=9): State=0

18:13:35.163443:OnSwitchCreated(EEID=0:208 IID=4): State=1

18:13:35.167035:OnSwitchCreated(EEID=0:245 IID=3): State=1

18:13:35.170904:OnSwitchCreated(EEID=0:279 IID=2): State=1

18:13:35.174988:OnSwitchCreated(EEID=0:284 IID=1): State=1

18:13:35.178820:OnSwitchCreated(EEID=0:1055 IID=6): State=1

18:13:35.182562:OnSwitchCreated(EEID=0:1114 IID=5): State=1

18:13:35.186046:OnEngineMonitorCreated(EEID=0:1691 IID=7): Thrust=0 RPM=0

18:13:35.189543:OnEngineControllerCreated(EEID=0:1692 IID=0)

18:13:35.193331:OnPowerProbeCreated(EEID=0:1697 IID=8): State=1

18:13:35.197244:Layout: decoratedW=19, decoratedH=1, W=19, H=1

18:13:35.198333:OnMainGLCanvasResize: 20x0

18:13:35.199275:OnMainGLCanvasResize: 20x0

18:13:35.220319:SplashScreenDialog::OnPaint()

18:13:35.230294:Post-Initialize took 9.56336s

18:13:35.388115:TODOTEST: disabled rendering (upload+rendering) @ GameController

18:13:35.399450:MainFrame::AfterGameRender: showing frame

18:13:36.283571:OnMainGLCanvasResize: 398x22


(FloatingSandbox:31193): Gtk-CRITICAL **: 18:13:36.311: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
18:13:36.312687:OnMainGLCanvasResize: 2x0

18:13:36.320489:OnMainGLCanvasResize: 2x0

18:13:36.322930:OnMainGLCanvasResize: 2x0

18:13:36.470667:OnMainGLCanvasResize: 1920x883

18:13:36.470905:OnMainGLCanvasResize: 1920x883

18:13:36.472723:OnMainGLCanvasResize: 1920x882

18:13:36.473072:OnMainGLCanvasResize: 1920x882

18:13:36.552905:RenderContext::RebindContext: start

18:13:36.581038:RenderContext::RebindContext: end

18:13:36.581179:MainFrame::OnMainGLCanvasPaint(): Hiding SplashScreen

18:13:45.837789:UpdateChecker: StatusCode=403
```
</details>

**Comment by GabrieleGiuseppini** [comment]
A-ha, for a moment I had a scare. It seems the pull didn't really go through, or the executable you're running is not the result of the build. Specifically, I was expecting to see this log line: https://github.com/GabrieleGiuseppini/Floating-Sandbox/blob/issue_41/Game/GameController.cpp#L409

Can you double-check?

**Comment by DonFlymoor** [comment]
# Maritime Disaster
----------------------
Error during initialization of game controller: Unrecognized 
GenericLinear texture group "DaylightCycleNotification"
----------------------

**Comment by GabrieleGiuseppini** [comment]
Still seems a botched pull :-( What do you see at this line: https://github.com/GabrieleGiuseppini/Floating-Sandbox/blob/issue_41/Game/TextureTypes.h#L166 ?

**Comment by DonFlymoor** [comment]
Sorry I've been gone for so long, I've had a lot going on and Raspbian just didn't want to cooperate. I've since changed my OS to Ubuntu mate (Works much better than Raspbian), and will try a fresh pull and build.

**Comment by GabrieleGiuseppini** [comment]
Hi Daniel, nice to see you back!
Sure, let me know how the build goes. 

I still plan to install Ubuntu myself on Virtualbox to try and produce a Linux build of FS, but I haven't gotten the time to do that yet.

**Comment by DonFlymoor** [comment]
There's no need for VirtualBox unless you're emulating another architecture. You can flash a live image of ubuntu to a usb, and boot from that.

**Comment by DonFlymoor** [comment]
I'm having trouble compiling this time... see #47

**Comment by GabrieleGiuseppini** [comment]
Finally, after so many months, I've got an Ubuntu running on VirtualBox and can reproduce. wxWidgets' menu's appear to not be working at all. Looking into it.

**Comment by DonFlymoor** [comment]
If you have a dedicated gpu, you should look into Windows Subsystem for
Linux, WSL is much faster for graphical applications, and is made by
Windows. You would need to join Windows Insider's to get the graphical
speedup though.

**Comment by GabrieleGiuseppini** [comment]
Thanks for the tip!

I've finally found out the root cause of this issue. On GTK, timer events appear to queue up, and thus if the game iteration takes longer than the timer step, the app is stuck executing game updates right after each other, with no chances of polling other events - like the menu-driving events - from the event loop.

Fix: on Linux only, queue a timer event at the _end_ of `OnGameTimerTrigger`, with duration equal to the max of `TimerDuration-elapsed` and - possibly - zero.

**Comment by GabrieleGiuseppini** [comment]
And finally it's fixed! All UI controls appear to be responsive now.
I'll be fixing some layout inaccuracies now, it seems some positions and sizes that work on Windows to not work on GTK .
